<h3>Here are all the exercises from exercise set 1.<h3>

<h3>Exercise 1.1<h3>

In [3]:
# Create a list to store 15 number ones 
ones = []

# Create for loop to append 15 number ones to the previously created list(ones) above
for x in range(15):
    ones.append(1)

# Create print to display the list of ones to the user
print(f"Here is 15 ones: {ones}")

# Create list to store 15 number sevens
sevens = []

# Create for loop to append 15 number sevens to the previously created list(sevens) above
for x in range(15):
    sevens.append(7)

# Create a print to display the 15 number sevens to the user
print(f"Here is 15 sevens: {sevens}")

# Create list to store numbers between 100-150
list100_150 = []

# Create for loop to append x to the previously created list, +1 to the x to create list(list100_150) of numbers between 100-150, +1 to 151 to get all,
# numbers between 100-150"
for x in range(100, 151):
    list100_150.append(x)
    x += 1

# Create print to display numbers between 100-150 to the user
print(f"Here is list of numbers between 100-150: {list100_150}")

# Create list to store even numbers between numbers 0-100
even_numbers = []

# Create for loop to calculate even numbers between 0-100, use if loop to append information to the privously created list
for x in range(0, 102):
    evens = x%2
    if evens == 0:
        even_numbers.append(x)

# Create print to display the list(even_numbers) of even numbers between 0-100 to the user
print(f"Here is list of even numbers between numbers 0-100: {even_numbers}")

# Create a list to store years divisable by 4
divisable_years = []

# Create for loop to calculate years divisable by 4 between years 1950-2020
for x in range(1950, 2024):
    years_divided = x%4
    if years_divided == 0:
        divisable_years.append(x)

# Create print to display the list(divisable_years) of years divisable by 4
print(f"Here are all the years divisable by number 4 between years 1950-2020: {divisable_years}")

Here is 15 ones: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Here is 15 sevens: [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
Here is list of numbers between 100-150: [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]
Here is list of even numbers between numbers 0-100: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
Here are all the years divisable by number 4 between years 1950-2020: [1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]


<h3>Under this markdown you can find all code imports to display all the following exercises!<h3>

In [4]:
# Import numpy as np, so it can be used in the following exercises
import numpy as np

In [5]:
%load_ext numpy_html

The numpy_html extension is already loaded. To reload it, use:
  %reload_ext numpy_html


In [6]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

<h2>Exercise 1.2<h2>


<h2>Following exercises have been created with the help of numpy.<h2>

In [7]:
# Create an array of 15 number 0
zeros = np.zeros((1, 15)).astype(int)

# Display the array
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
# Create an array of 15 number 1
ones = np.ones((1, 15)).astype(int)

# Display the array
ones

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [9]:
# Create an array of 15 number 7
sevens = np.zeros((1, 15)).astype(int) + 7

# Display the array
sevens

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [10]:
# Create an array of numbers between 100-150, +1 to 150 to get all numbers between the numbers
num100_150 = np.arange(100, 151)

# Display the array
num100_150

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [11]:
# Create an array of between numbers 1900-2021, +1 to the 2021 to get all numbers between numbers 1900-2021
num1900_2020 = np.arange(1900, 2022)

# Display the array
num1900_2020

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [12]:
# Create an array of even numbers between 0-100 with the help of numpy
num0_100_numpy = np.arange(0, 102, 2)

# Display the array
num0_100_numpy

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
# Create an array of years divisable by 4 between years 1950-2020
numpy_divi_years = np.arange(1950, 2022, 4)

# Display the array
numpy_divi_years

array([1950, 1954, 1958, 1962, 1966, 1970, 1974, 1978, 1982, 1986, 1990,
       1994, 1998, 2002, 2006, 2010, 2014, 2018])

<h2>Exercise 1.3<h2>

In [14]:
# Create a vector list of numbers(5, 16, 9, 2, 19, 18, 7)
vector_list = ([5, 16, 9, 2, 19, 18, 11, 7])

# Create a sentence, which finds max position of largest value in the vector
vect_listmax = np.argmax(vector_list)

# Display the vector listmax
vect_listmax

4

In [15]:
# Create 7x7 matrix of values between 1-49
matrix_1_3b = np.arange(1,50).reshape(7, 7)

# Display the 7x7 matrix for 1.3b
matrix_1_3b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [16]:
# Create a 8x8 matrix of random numbers
matrix1_3c = np.random.randint(0, 5, 64).reshape(8, 8)

# Display the 8x8 matrix for 1.3c
matrix1_3c

array([[1, 4, 4, 1, 4, 0, 4, 0],
       [3, 3, 0, 1, 0, 2, 1, 2],
       [4, 4, 2, 1, 2, 2, 3, 1],
       [3, 4, 3, 2, 3, 0, 4, 2],
       [2, 0, 2, 4, 3, 0, 1, 1],
       [0, 1, 1, 3, 3, 0, 4, 4],
       [4, 4, 4, 2, 0, 4, 0, 2],
       [1, 0, 3, 1, 0, 4, 3, 3]])

In [60]:
# Create 8x8 matrix of random numbers by using standard normal distributions(values between -3 and 3)
random_matrix1_3d = np.random.randn(3)
random_matrix1_3d = np.random.randn(8, 8)

# Display the 8x8 matrix for 1.3d
random_matrix1_3d

array([[ 1.83984123,  2.07550733,  0.2249396 , -0.81446074, -1.40110413,
         0.22419312, -0.43116466, -0.76733342],
       [-2.46288491, -0.97361958, -1.00204362,  2.05608074,  2.27109927,
         0.40277347, -1.00808351, -0.79687479],
       [-0.2706746 , -0.53378345, -0.91216261,  1.13207128,  0.40207058,
         1.44596908, -2.12128087, -0.12957957],
       [-1.14333116, -0.15345804,  0.70908882, -1.25923849,  1.94337905,
         1.01798181,  1.51870789, -1.38175529],
       [-0.27921409,  1.16781353,  0.52268226, -0.33512344,  0.12204844,
        -0.33114479, -0.14065512,  1.3771914 ],
       [-2.32199873, -1.42092724,  1.14700683, -1.37879224,  0.99532959,
         0.99179651, -0.01394581,  1.0758963 ],
       [-0.9013437 , -0.52823966, -1.64405395, -0.67932581, -0.39463224,
        -0.88692744, -1.28175421,  0.61804663],
       [ 1.43515773, -0.10770209,  0.98107218, -1.30593642,  0.40102996,
        -0.13577736,  0.66387625, -1.8518061 ]])

<h2>Exercise 1.4<h2>

In [18]:
# Create array of 10 values between 0 and 1 with the help of linspace
zero_to_one = np.linspace(0, 1, 10)
zero_to_one_matrix = zero_to_one.reshape(2, 5)

# Display the matrix
zero_to_one_matrix

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444],
       [0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]])

In [19]:
# Create a 10x10 matrix of all values between 0 and 5 by using linspace
one_to_five = np.linspace(0, 5, 100)
one_to_five_matrix = one_to_five.reshape(10, 10)

# Display the matrix
one_to_five_matrix

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737374,
        3.78787879, 3.83838384, 3.88888889, 3.93939394, 3.98989899],
       [4.04040404, 4.09090909, 4.14141414, 4.19191919, 4.24242424,
        4.29292929, 4.34343434, 4.39393939, 4.44444444, 4.49494949],
       [4.54545455, 4.5959596 , 4.64646465, 4.6969697 , 4.74747475,
        4.7979798 , 4.84848485, 4.8989899 , 4.94949495, 5.        ]])

<h2>Exercise 1.5<h2>

In [49]:
# Create a 3x5 matrix from values(23, 34, 54, 75, 33, 56, 78, 65, 97, 41, 32, 11, 39, 51)
numbers_1_5a = ([23, 34, 54, 31, 75, 33, 56, 78, 65, 97, 41, 32, 11, 39, 51])
array_1_5a = np.array(numbers_1_5a).reshape(3, 5)

# Display the matrix
print("(3, 5)")
array_1_5a

(3, 5)


array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

In [48]:
# Create a 8x16 matrix from values between  128-256
matrix1_5b = np.arange(128, 256).reshape(8, 16)

# Display the matrix
print("(8, 16)")
matrix1_5b

(8, 16)


array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

In [47]:
# Create 10x10 matrix from values between 0 and 5 with 0.05 increase to previous value
matrix1_5c = np.linspace(0.05, 5, 100).reshape(10, 10)

# Display the matrix
print("(10, 10)")
matrix1_5c


(10, 10)


array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

<h2>Exercise 1.6<h2>

In [89]:
# Create 6x6 matrix called dataset from numbers between 1-36
dataset = np.arange(1, 37).reshape(6, 6)

# Display the dataset
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [24]:
# Create a function to get values(21-36) from the data set, column 4 row 3 to column 6 row 6
matrix_1 = dataset[3:6, 2:6]

# Display the matrix
matrix_1

array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

In [25]:
# Create a function to get values(4, 10, 16 and 22) from the dataset, column 1 row 4 to column 4 row 4
matrix_2 = dataset[0:4, 3]

# Display the matrix
matrix_2

array([ 4, 10, 16, 22])

In [26]:
# Create a function to get values from 3rd column
matrix_3 = dataset[2]

# Display the matrix
matrix_3

array([13, 14, 15, 16, 17, 18])

In [27]:
# Get values from 4th to 7th row
matrix_4 = dataset[3:6]

# Display the matrix
matrix_4

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h2>Exercise 1.7<h2>

In [63]:
# Create matrix from values between 1-50 in 7x7
dataset = np.arange(1, 50).reshape(7, 7)

# Display the dataset
dataset

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [64]:
# Add + 50 to all numers into the matrix previously created
new_dataset = dataset + 50

# Display the new dataset
new_dataset

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [66]:
# Create sentence to get sum of all numbers in the matrix
dataset_total1 = np.sum(new_dataset)

# Display the dataset_total1 sum
dataset_total1

3675

In [68]:
# Create a function to get total of odd values in the dataset
odd_values = new_dataset % 2 != 0
odd_array = new_dataset[odd_values]
odd_values_total = np.sum(odd_array)

# Display the odd values total in the dataset
odd_values_total

1875

In [69]:
# Create a function to get standard deviation of dataset_values
dataset_deviation = np.std(new_dataset)

# Display the dataset deviation
dataset_deviation

14.142135623730951

In [70]:
# Create a function to get sum by a row
dataset_matrix = np.arange(1, 50).reshape(7, 7)
dataset_3total = np.sum(new_dataset, axis=1)

# Display the dataset_3total
dataset_3total

array([378, 427, 476, 525, 574, 623, 672])

In [80]:
# Create a function to get sum by a column
dataset_4total = np.sum(new_dataset, axis=0)
dataset_4total

array([504, 511, 518, 525, 532, 539, 546])

In [96]:
# Create variable to store the sum of each row within the dataset
row_sums = []

# Create for loop to go through the new_dataset and sum row containtments together, append the sum of each row into the storage variable above
for row in new_dataset:
    row_sum = sum(row)
    row_sums.append(row_sum)

# Create text to inform user about what the information is for
print("Sum of containtments of each row within the dataset:")
    
# Create for loop to go through each row, enumerate them and print each row one by one
for i, row_sum in enumerate(row_sums):
    print(row_sum)

Sum of containtments of each row within the dataset:
378
427
476
525
574
623
672


In [87]:
# Create variable to store the sum of each column within the dataset
column_sums = [0] * len(new_dataset[0])

# Create for loop to go through the new_dataset and sum column values containtments together, append the sum of each column values into the storage variable above
for row in new_dataset:
    for i, value in enumerate(row):
        column_sums[i] += value
        
# Create for loop to go through each column, enumerate them and print each row one by one
for i, column_sum in enumerate(column_sums):
    print(column_sum)

504
511
518
525
532
539
546


<h2>Here are all extra exercises from exercise set 1.<h2>

<h3>1.3b extra<h3>

In [35]:
# Create a list to store values of the matrix
matrix = []

# Create starting value to be used in creating the variables
start_value = 1

# Create a statement to define values of rows in the matrix
for x in range(7):
    row = []
    # Create statement to add +1 to starting value and add starting value into row
    for x in range(7):
        row.append(start_value)
        start_value += 1
    # Add row into the matrix
    matrix.append(row)

# Create statement to display matrix
for row in matrix:
    print(row)


[1, 2, 3, 4, 5, 6, 7]
[8, 9, 10, 11, 12, 13, 14]
[15, 16, 17, 18, 19, 20, 21]
[22, 23, 24, 25, 26, 27, 28]
[29, 30, 31, 32, 33, 34, 35]
[36, 37, 38, 39, 40, 41, 42]
[43, 44, 45, 46, 47, 48, 49]


<h3>1.4b extra<h3>

In [88]:
# Create a function to calculate linearly spaced list
def linspace(start, stop, num):
    # Calculate the step size
    values = (stop - start) / (num - 1)
    values_list = []
    # Generate linearly spaced values and append them to the result list
    for i in range(num):
        values_list.append(start + values * i)
    return values_list

# Generate linearly spaced list between 0 and 5 with 100 values
matrix_05values = linspace(0.05, 5, 100)

# Create a list to store the 10x10 matrix
matrix_05 = []
# Create statement to create rows into the matrix list, there are 10 rows, which each hold 10 values
for i in range(0, 100, 10):
    # Slice the list into 10 rows and add them to the matrix list
    row = matrix_05values[i:i+10]
    matrix_05.append(row)

# Create statement to display the result to the user
for row in matrix_05:
    print(row)


[0.05, 0.1, 0.15000000000000002, 0.2, 0.25, 0.3, 0.35000000000000003, 0.4, 0.45, 0.5]
[0.55, 0.6000000000000001, 0.6500000000000001, 0.7000000000000001, 0.7500000000000001, 0.8, 0.8500000000000001, 0.9000000000000001, 0.9500000000000001, 1.0]
[1.05, 1.1, 1.1500000000000001, 1.2000000000000002, 1.2500000000000002, 1.3, 1.35, 1.4000000000000001, 1.4500000000000002, 1.5000000000000002]
[1.55, 1.6, 1.6500000000000001, 1.7000000000000002, 1.7500000000000002, 1.8, 1.85, 1.9000000000000001, 1.9500000000000002, 2.0]
[2.05, 2.1, 2.15, 2.1999999999999997, 2.25, 2.3, 2.35, 2.4, 2.45, 2.5]
[2.55, 2.6, 2.65, 2.7, 2.75, 2.8, 2.85, 2.9, 2.95, 3.0]
[3.05, 3.1, 3.15, 3.2, 3.25, 3.3, 3.35, 3.4, 3.45, 3.5]
[3.55, 3.6, 3.65, 3.7, 3.75, 3.8, 3.85, 3.9, 3.95, 4.0]
[4.05, 4.1, 4.15, 4.2, 4.25, 4.3, 4.35, 4.4, 4.45, 4.5]
[4.55, 4.6, 4.65, 4.7, 4.75, 4.8, 4.8500000000000005, 4.9, 4.95, 5.0]


Advanced exercises 

1.1

In [98]:
# Create a 15x15 matrix
matrix = np.random.random((15, 15))

# Save the matrix to a file (matrix.txt)
np.savetxt('matrix.txt', matrix)

In [102]:
# Load matrix.txt and store it into variable
loaded_matrix = np.loadtxt('matrix.txt')

# Convert it back to a NumPy matrix
loaded_matrix = np.matrix(loaded_matrix)

# Display using print
print(loaded_matrix)

[[0.3092725  0.86438159 0.06427758 0.30303947 0.42707657 0.44159115
  0.84319612 0.93282498 0.57385876 0.56604426 0.91422164 0.08719277
  0.91656103 0.13152739 0.36701734]
 [0.31212052 0.42913563 0.32823435 0.67336475 0.65272037 0.65949147
  0.74870622 0.64323509 0.61678311 0.63930664 0.47618145 0.37949879
  0.79839227 0.04325364 0.40996743]
 [0.15314005 0.58437595 0.15716345 0.516737   0.87917892 0.90046055
  0.86682534 0.76804564 0.23525519 0.99581618 0.20911781 0.80606391
  0.21201669 0.22258413 0.80483278]
 [0.08822831 0.11260455 0.44132344 0.79136747 0.51653972 0.6281723
  0.43811666 0.59402165 0.96524834 0.75250614 0.86628747 0.20791977
  0.79484212 0.99175317 0.17330243]
 [0.80442265 0.85366386 0.97839709 0.45508854 0.91504016 0.39226181
  0.38479739 0.21735771 0.14680619 0.6952212  0.53949496 0.27885575
  0.93796739 0.55747757 0.86467094]
 [0.62383946 0.75662972 0.11376635 0.98702771 0.38567713 0.58916616
  0.6035494  0.14523382 0.69196139 0.93470522 0.98313223 0.88491048
  0.8

In [103]:
# Display the loaded_matrix
loaded_matrix

matrix([[0.3092725 , 0.86438159, 0.06427758, 0.30303947, 0.42707657,
         0.44159115, 0.84319612, 0.93282498, 0.57385876, 0.56604426,
         0.91422164, 0.08719277, 0.91656103, 0.13152739, 0.36701734],
        [0.31212052, 0.42913563, 0.32823435, 0.67336475, 0.65272037,
         0.65949147, 0.74870622, 0.64323509, 0.61678311, 0.63930664,
         0.47618145, 0.37949879, 0.79839227, 0.04325364, 0.40996743],
        [0.15314005, 0.58437595, 0.15716345, 0.516737  , 0.87917892,
         0.90046055, 0.86682534, 0.76804564, 0.23525519, 0.99581618,
         0.20911781, 0.80606391, 0.21201669, 0.22258413, 0.80483278],
        [0.08822831, 0.11260455, 0.44132344, 0.79136747, 0.51653972,
         0.6281723 , 0.43811666, 0.59402165, 0.96524834, 0.75250614,
         0.86628747, 0.20791977, 0.79484212, 0.99175317, 0.17330243],
        [0.80442265, 0.85366386, 0.97839709, 0.45508854, 0.91504016,
         0.39226181, 0.38479739, 0.21735771, 0.14680619, 0.6952212 ,
         0.53949496, 0.27885575, 0.93796739, 0.55747757, 0.86467094],
        [0.62383946, 0.75662972, 0.11376635, 0.98702771, 0.38567713,
         0.58916616, 0.6035494 , 0.14523382, 0.69196139, 0.93470522,
         0.98313223, 0.88491048, 0.8555154 , 0.43752694, 0.01599754],
        [0.22479506, 0.32554615, 0.91592313, 0.08858546, 0.58779343,
         0.68400983, 0.93681671, 0.9711244 , 0.24012737, 0.00698104,
         0.05646156, 0.14774048, 0.97034388, 0.49476108, 0.97503811],
        [0.20788983, 0.04991852, 0.67878894, 0.27030011, 0.95350324,
         0.23909446, 0.21841504, 0.53362429, 0.19980814, 0.94754122,
         0.76426383, 0.14795243, 0.81498488, 0.40154112, 0.09535274],
        [0.83143689, 0.80409544, 0.08731213, 0.23629946, 0.23080654,
         0.85765823, 0.04497526, 0.09961171, 0.91827544, 0.12703649,
         0.08464704, 0.86545237, 0.84679894, 0.84895635, 0.24557953],
        [0.4827562 , 0.95577792, 0.21740699, 0.41666753, 0.36910905,
         0.06217678, 0.54942784, 0.03912046, 0.22019813, 0.98876253,
         0.46549171, 0.96737236, 0.61499522, 0.63765507, 0.12044969],
        [0.17561472, 0.09689757, 0.73944732, 0.62280423, 0.78127326,
         0.4302757 , 0.92334108, 0.27144127, 0.34719949, 0.73651068,
         0.06301817, 0.55913985, 0.3513749 , 0.82829948, 0.04838732],
        [0.2894491 , 0.11454106, 0.14507615, 0.77683092, 0.38448403,
         0.31094842, 0.89938702, 0.28929846, 0.34871757, 0.20841812,
         0.82105644, 0.5060315 , 0.11633233, 0.72988547, 0.84885753],
        [0.13498144, 0.32228847, 0.86414983, 0.54579219, 0.21273502,
         0.75028158, 0.79991298, 0.09738929, 0.79065883, 0.23436421,
         0.17342342, 0.28254157, 0.08906852, 0.05329675, 0.41891995],
        [0.58752368, 0.42352998, 0.9573744 , 0.22820967, 0.7035183 ,
         0.02763895, 0.18019966, 0.62910628, 0.32104552, 0.28524139,
         0.13694245, 0.06321044, 0.3106629 , 0.88137187, 0.9710646 ],
        [0.32116691, 0.61634973, 0.46979306, 0.05538032, 0.52579071,
         0.71863007, 0.50028123, 0.41934393, 0.26989464, 0.73044651,
         0.23852573, 0.37792096, 0.01065079, 0.47152477, 0.54717553]])

In [123]:
# Create variable for 5x10 matrix, for the matrix use random numbers from 0-50,
matrix = np.random.randint(0, 50, (5, 10))

# Create for loop to go through the matrix values and put faulty numbers(-100) to some of them
for i in range(10):
    x, y = np.random.randint(0, 5, 2)
    matrix[x, y] = -100

# Create a masked array to handle the -100 values
masked_matrix = np.ma.masked_equal(matrix, -100)

# Replace every -100 with 0
masked_matrix = np.ma.filled(masked_matrix, 0)

# Print the original matrix and the masked matrix
print("Original matrix with faulty numbers:")
print(matrix)
print("Masked matrix with faulty numbers replaced:")
print(masked_matrix)

array([[40, 46,  5,  7, 41,  3, 37, 28, 42, 34],
       [49, 35,  3, 43, 49, 47, 12, 42, 34, 23],
       [46,  9, 49, 36,  0,  3, 48, 44, 47,  8],
       [21, 47, 42, 18, 19, 30, 44, 15, 20,  2],
       [25, 13,  9, 37, 28, 47,  1, 48, 24, 28]])

In [125]:
# Create dataset years, use random randint for years between 2010-2021
years = np.random.randint(2010, 2021, 10)

# Create dataset prices, use random randint for prices between 2000-60000
prices = np.random.randint(2000, 60000, 10)

# Sort both datasets according to years
sort_arg = np.argsort(years)
years = years[sort_arg]
prices = prices[sort_arg]

# Display both of the sorted datasets
print("Manufacturing years:")
print(years)
print("Selling prices:")
print(prices)

Manufacturing years:
[2010 2011 2011 2012 2014 2015 2016 2017 2018 2019]
Selling prices:
[48538 59232  3643 44872 51583 59053 14768 24805 14438 48414]


In [126]:
# Create array of 
advanced4_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Display the advanced_array
advanced4_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [127]:
# Try np.repeat() function
advanced4_repeated = np.repeat(advanced4_array, 3)
print(advanced4_repeated)

[ 1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  6  6  7  7  7  8  8  8
  9  9  9 10 10 10 11 11 11 12 12 12]


In [128]:
# Try np.ravel() function
advanced4_flattened = np.ravel(advanced4_array)
print(advanced4_flattened)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [129]:
# Try np.hsplit() function
advanced4_hsplit = np.hsplit(advanced4_array, 2)
print(advanced4_hsplit)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [130]:
# Try np.vsplit() function
advanced4_vsplit = np.vsplit(advanced4_array, 3)
print(advanced4_vsplit)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [131]:
# Try np.hstack() function
advanced4_hstack = np.hstack(advanced4_hsplit)
print(advanced4_hstack)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [132]:
# Try np.vstack() function
advanced4_vstack = np.vstack(advanced4_vsplit)
print(advanced4_vstack)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [133]:
# Try np.transpose() function
advanced4_array_transposed = np.transpose(advanced4_array)
print(advanced4_array_transposed)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [137]:
# Try np.round() function
advanced4_rounded_array = np.round(advanced4_array, decimals=2)
print("Rounded Array:\n", advanced4_rounded_array)

Rounded Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [139]:
# Try np.expanded() function
advanced4_expanded_array = np.expand_dims(advanced4_array, axis=2)
print("Expanded Array:\n", advanced4_expanded_array)

Expanded Array:
 [[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [140]:
# Try np.squeezed() function
advanced4_squeezed_array = np.squeeze(advanced4_expanded_array, axis=2)
print("Squeezed Array:\n", advanced4_squeezed_array)

Squeezed Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [142]:
# Try np.digitize() function
bins = [0, 4, 8, 12]
advanced4_digitized_array = np.digitize(advanced4_array, bins)
print("Digitized Array:\n", advanced4_digitized_array)

Digitized Array:
 [[1 1 1 2]
 [2 2 2 3]
 [3 3 3 4]]
